services:
  # Frontend Angular (build + Nginx)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-app
    restart: always
    ports:
      - "8083:80"   # Acesse via http://SEU-IP:8083
    networks:
      - gestao-os-network

networks:
  gestao-os-network:
    external: true   # Rede criada previamente no Portainer (Networks -> Add network)
